export const SAVE_AUTH = 'SAVE_AUTH'
export const RESET_AUTH = 'RESET_AUTH'

export const SAVE_STATE_STEP1_REGISTER = 'SAVE_STATE_STEP1_REGISTER'
export const SAVE_STATE_STEP2_REGISTER = 'SAVE_STATE_STEP2_REGISTER'
export const SAVE_STATE_STEP3_REGISTER = 'SAVE_STATE_STEP3_REGISTER'
export const SET_STEP_REGISTER = 'SET_STEP_REGISTER'
export const RESET_STATE_REGISTER = 'RESET_STATE_REGISTER'